name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - blas
  - brotli
  - bzip2
  - ca-certificates
  - contourpy
  - cycler
  - fonttools
  - freetype
  - jpeg
  - kiwisolver
  - lcms2
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcxx
  - libdeflate
  - libffi
  - libgfortran
  - libgfortran5
  - libopenblas
  - libpng
  - libtiff
  - libwebp-base
  - llvm-openmp
  - lz4-c
  - matplotlib
  - matplotlib-base
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - packaging
  - pillow
  - pip
  - pyparsing
  - python=3.10
  - python-dateutil
  - setuptools
  - six
  - sqlite
  - tk
  - tornado
  - unicodedata2
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
      - filelock==3.16.1
      - fire==0.7.0
      - fsspec==2024.10.0
      - imageio==2.36.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - lazy-loader==0.4
      - markupsafe==3.0.2
      - medmnist==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - pandas==2.2.3
      - pytz==2024.2
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - sympy==1.13.1
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - torch==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
